FROM python:3.12.3

ARG JWT_SECRET_KEY
ARG OPENSEARCH_URL
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV OPENSEARCH_URL=$OPENSEARCH_URL
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

WORKDIR /balbalm

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY /app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
