name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build . \
          --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          --build-arg OPENSEARCH_URL=${{ vars.OPENSEARCH_URL }} \
          --build-arg AWS_ACCESS_KEY_ID=${{ secrets.OPENSEARCH_ACCESS_KEY_ID }} \
          --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.OPENSEARCH_SECRET_ACCESS_KEY }} \
          -t 147997130241.dkr.ecr.ap-northeast-2.amazonaws.com/balbalm/backend-place:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image
        run: |
          docker push 147997130241.dkr.ecr.ap-northeast-2.amazonaws.com/balbalm/backend-place:latest

      - name: Deploy to EKS
        run: |
          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }}
          kubectl rollout restart deployment -n devocean balbalm-user
